
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://akshay-gupta123.github.io/akshay-gupta123.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""
cv: "YugeshAjitKothari.pdf"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Akshay Gupta"
title: "# Akshay Gupta #"
description: "BE THE CHANGE,RATHER TO BRING IT - Akshay Gupta"
keywords: "akshay, gupta"
favicon: "/img/geek.png"

################
# Header layout #
################

black-favicon: "/img/geek.png"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 8
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "Life is too short to write documentation."
  - text: "Just kidding, go document your code."
  - text: "Talk is Cheap , Where is Your Code ?"

me-img: "/img/author.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
# google-plus-share: True
# tumblr-share: True
pinterest-share: True
pocket-share: True
# vkontakte-share: True

# disqus-shortname: "yugesh-kothari"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/iitk.png"
    date: "July 2019 - Present"
    description: "Student(Under Graduate) \n At IITK"
  - image: "/img/timeline/amu.jpg"
    date: "May 2016 - July 2018"
    description: "Student(Intermediate) \n At Sayyid Hamid School,AMU"
  - image: "/img/timeline/rrk.jpg"
    date: "May 2016 - July 2018"
    description: "Student(SSC) \n R.R.K. Sen. Sec. School"

# First image of the Timeline

timeline-img: "/img/timeline/iitk.png"

###########
# Contact #
###########

email: "akshay.bis2000@gmail.com"
phone: +91-9411459662

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Akshay is a First year CS undergrad at IIT Kanpur. He's passionate about technology and loves doing lots of coding."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/gupta.akshay123"
  - title: "linkedin"
    url: "https://linkedin.com/in/akshay18082001"
  - title: "github"
    url: "https://github.com/akshay-gupta123"

############
# 404 page #
############

err-404-img: "/img/geek_old.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'
  Resume: 'cv'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
